### Map entities
doctrine:
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Color:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/bolt/color/src'
        prefix: 'Bolt\Color'
        alias: Color